name: month_view

on:
  push:
    branches:
      - main  # Этот workflow запускается при пуше в основную ветку
  schedule:
    - cron: '0 0 * * *'  # Работает каждый день в полночь по UTC

jobs:
  fetch_traffic:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch traffic data from GitHub API
      id: fetch_traffic
      run: |
        # Получаем данные о трафике с GitHub API, используя переменную ${{ github.repository }}
        response=$(curl -H "Authorization: token ${{ secrets.PUBLIC_REPO_TOKEN }}" \
                         -H "Accept: application/vnd.github.v3+json" \
                         https://api.github.com/repos/${{ github.repository }}/traffic/views)

        # Извлекаем общее количество просмотров и уникальных просмотров
        total_views=$(echo "$response" | jq '.count')
        unique_views=$(echo "$response" | jq '.uniques')

        if [ -f READMEview.md ]; then
          # Используем sed для замены строк, содержащих "Общее количество просмотров" и "Уникальные просмотры"
          sed -i "s/Общее количество просмотров за месяц:.*/Общее количество просмотров за месяц: $total_views/" READMEview.md
          sed -i "s/Уникальные просмотры за месяц:.*/Уникальные просмотры за месяц: $unique_views/" READMEview.md
        else
          # Если файл не существует, создаем новый файл
          echo "Общее количество просмотров за месяц: $total_views" > READMEview.md
          echo "Уникальные просмотры за месяц: $unique_views" >> READMEview.md
        fi


    - name: Set git configuration
      run: |
        git config --global user.name "cortez24rus"
        git config --global user.email "cortez24rus@gmail.com"

    - name: Pull latest changes
      run: |
        git pull origin main || echo "No changes to pull"

    - name: Commit and push changes to READMEview.md
      run: |
        git add READMEview.md
        git commit -m "Update traffic data in READMEview.md" || echo "No changes to commit"
        git push origin main