name: Fetch Traffic Data

on:
  push:
    branches:
      - main  # Этот workflow запускается при пуше в основную ветку

jobs:
  fetch_traffic:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch traffic data from GitHub API
      id: fetch_traffic
      run: |
        # Получаем данные о трафике с GitHub API, используя переменную ${{ github.repository }}
        response=$(curl -H "Authorization: token ${{ secrets.PUBLIC_REPO_TOKEN }}" \
                         -H "Accept: application/vnd.github.v3+json" \
                         https://api.github.com/repos/${{ github.repository }}/traffic/views)

        # Извлекаем общее количество просмотров и уникальных просмотров
        total_views=$(echo "$response" | jq '.count')
        unique_views=$(echo "$response" | jq '.uniques')

        # Форматируем данные для записи в READMEview.md
        echo "Общее количество просмотров: $total_views" > READMEview.md
        echo "Уникальные просмотры: $unique_views" >> READMEview.md

    - name: Set git configuration
      run: |
        git config --global user.name "cortez24rus"
        git config --global user.email "cortez24rus@gmail.com"

    - name: Pull latest changes
      run: |
        git pull origin main || echo "No changes to pull"

    - name: Commit and push changes to READMEview.md
      run: |
        git add READMEview.md
        git commit -m "Update traffic data in READMEview.md" || echo "No changes to commit"
        git push origin main