name: Fetch Traffic Data

on:
  push:
    branches:
      - main  # Этот workflow запускается при пуше в основную ветку

jobs:
  fetch_traffic:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch traffic data from GitHub API
      run: |
        curl -H "Authorization: token ${{secrets.public_repo_token}}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/cortez24rus/xui-reverse-proxy/traffic/views