jobs:
  fetch_traffic:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install jq

    - name: Fetch traffic data from GitHub API
      id: traffic
      run: |
        response=$(curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
                        -H "Accept: application/vnd.github.v3+json" \
                        https://api.github.com/repos/cortez24rus/xui-reverse-proxy/traffic/views)
        echo "::set-output name=view_count::$(echo $response | jq '.count')"
    
    - name: Update README with traffic data
      run: |
        sed -i 's|<!-- traffic_count -->|Views: ${{ steps.traffic.outputs.view_count }}|' README.md
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add README.md
        git commit -m "Update traffic data"
        git push
