name: Update README with traffic statistics

on:
  schedule:
    - cron: "0 0 * * *"  # Обновление каждый день в полночь (по вашему желанию)
  workflow_dispatch:  # Можно запускать вручную через интерфейс GitHub

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Checkout репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Получение данных о просмотрах
      - name: Get views data
        id: views
        run: |
          response=$(curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/cortez24rus/xui-reverse-proxy/traffic/views)
          total_views=$(echo "$response" | jq '.count')
          unique_views=$(echo "$response" | jq '.uniques')
          views_data=$(echo "$response" | jq -r '.views[] | "- " + .timestamp + ": " + (.count|tostring) + " просмотров (" + (.uniques|tostring) + " уникальных)"')
          
          echo "total_views=$total_views" >> $GITHUB_ENV
          echo "unique_views=$unique_views" >> $GITHUB_ENV
          echo "views_data=$views_data" >> $GITHUB_ENV

      # Обновление README.md с новой статистикой
      - name: Update README
        run: |
          readme_content=$(cat README.md)
          updated_readme=$(echo "$readme_content" | sed \
            "s/Общее количество просмотров репозитория: \*\*TBD\*\*/Общее количество просмотров репозитория: \*\*${{ env.total_views }}\*\*/" \
            | sed "s/Уникальные просмотры: \*\*TBD\*\*/Уникальные просмотры: \*\*${{ env.unique_views }}\*\*/" \
            | sed "s|TBD|${{ env.views_data }}|")
          echo "$updated_readme" > README.md

      # Коммит и пуш изменений
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update views statistics in README"
          git push
